const types = {    
    GLOBAL_STATUS_NONUSER_TOKEN : 'GLOBAL_STATUS_NONUSER_TOKEN',
    GLOBAL_STATUS_USER_TOKEN : 'GLOBAL_STATUS_USER_TOKEN',
    GLOBAL_STATUS_USER_FCM_TOKEN : 'GLOBAL_STATUS_USER_FCM_TOKEN',
    GLOBAL_STATUS_MAP_CONDITION : 'GLOBAL_STATUS_MAP_CONDITION',
    GLOBAL_STATUS_MAP_SUB_CONDITION : 'GLOBAL_STATUS_MAP_SUB_CONDITION',
    GLOBAL_STATUS_TOGGLE_VIEW_FAST_DEAL : 'GLOBAL_STATUS_TOGGLE_VIEW_FAST_DEAL',
    GLOBAL_STATUS_TOGGLE_APART_BOOKMARK : 'GLOBAL_STATUS_TOGGLE_APART_BOOKMARK',
    GLOBAL_STATUS_TOGGLE_VIEW_MYAGENT : 'GLOBAL_STATUS_TOGGLE_VIEW_MYAGENT',
    GLOBAL_STATUS_TOGGLE_AGENT_BOOKMARK : 'GLOBAL_STATUS_TOGGLE_AGENT_BOOKMARK',
    GLOBAL_STATUS_MAIN_MAP_SHOW : 'GLOBAL_STATUS_MAIN_MAP_SHOW',
    GLOBAL_STATUS_MAIN_MAP_TYPE : 'GLOBAL_STATUS_MAIN_MAP_TYPE',
    GLOBAL_STATUS_IS_RELOAD_MODE : 'GLOBAL_STATUS_IS_RELOAD_MODE',
    GLOBAL_STATUS_ROOT_STACK : 'GLOBAL_STATUS_ROOT_STACK',
    GLOBAL_STATUS_USER_BASE_DATA : 'GLOBAL_STATUS_USER_BASE_DATA',
    GLOBAL_STATUS_USER_BASE_DATA2 : 'GLOBAL_STATUS_USER_BASE_DATA2',
    GLOBAL_STATUS_TOGGLE_SEARCH_FORM : 'GLOBAL_STATUS_TOGGLE_SEARCH_FORM',
    GLOBAL_STATUS_TOGGLE_MY_ARTICLE : 'GLOBAL_STATUS_TOGGLE_MY_ARTICLE',
    GLOBAL_STATUS_SHOW_CHAT_TOAST : 'GLOBAL_STATUS_SHOW_CHAT_TOAST',
    GLOBAL_STATUS_SHOW_MAP_TOAST : 'GLOBAL_STATUS_SHOW_MAP_TOAST'
    
}

export default types;
