require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'goodagent' do
  config = use_native_modules!
  pod 'KakaoOpenSDK', '~> 1.21.0' # append this line
  pod 'RNIap', :path => '../node_modules/react-native-iap'
  use_react_native!(:path => config["reactNativePath"])
  source 'https://cdn.cocoapods.org/'
  

  target 'goodagentTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
        post_install do |installer|
            installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
        end
    end
end

target 'goodagent-tvOS' do
  # Pods for goodagent-tvOS

  target 'goodagent-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
